spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
    url: jdbc:mysql://localhost:3307/spring?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect